// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { QaError } from '@qa-ai-stlc/core';
import type { LocatorCandidate, SelectorElement, SelectorRegistry } from '@qa-ai-stlc/schemas';

export interface GenerateLocatorModuleOptions {
  /** Stamped into the module header and `GENERATOR_VERSION` so a stale file can be detected. */
  readonly generatorVersion: string;
}

export interface MissingLocatorElement {
  readonly elementId: string;
  readonly kind: string;
}

export interface GenerateLocatorModuleResult {
  /** The `tests/qa/locators.ts` file contents (ADR-006), ready to write as-is. */
  readonly source: string;
  /** Elements with no export: no locator candidate, or no export name assigned yet. */
  readonly missingLocators: readonly MissingLocatorElement[];
}

function roleCall(candidate: LocatorCandidate): string {
  const parsed: unknown = JSON.parse(candidate.value);
  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    !('role' in parsed) ||
    !('name' in parsed) ||
    typeof parsed.role !== 'string' ||
    typeof parsed.name !== 'string'
  ) {
    throw new QaError(
      'explorer.locator_module.invalid_role_candidate',
      `role candidate value is not a {role, name} pair: ${candidate.value}`,
    );
  }
  return `page.getByRole(${JSON.stringify(parsed.role)}, { name: ${JSON.stringify(parsed.name)} })`;
}

function locatorCall(candidate: LocatorCandidate): string {
  switch (candidate.strategy) {
    case 'role':
      return roleCall(candidate);
    case 'testId':
      return `page.getByTestId(${JSON.stringify(candidate.value)})`;
    case 'label':
      return `page.getByLabel(${JSON.stringify(candidate.value)})`;
    case 'placeholder':
      return `page.getByPlaceholder(${JSON.stringify(candidate.value)})`;
    case 'text':
      return `page.getByText(${JSON.stringify(candidate.value)})`;
    case 'css':
      return `page.locator(${JSON.stringify(candidate.value)})`;
    default:
      throw new QaError(
        'explorer.locator_module.unknown_strategy',
        `unknown locator strategy: ${candidate.strategy}`,
      );
  }
}

function isGeneratable(element: SelectorElement): element is SelectorElement & { name: string } {
  return element.name !== undefined && element.deprecatedAt === undefined;
}

function byName(a: { readonly name: string }, b: { readonly name: string }): number {
  return a.name.localeCompare(b.name);
}

/**
 * Renders the selector registry into a typed, deterministic `tests/qa/locators.ts` module (ADR-006):
 * one exported function per element, named after its registry `name`, returning a Playwright
 * `Locator` built from the element's primary (highest-preference) candidate. An element with no
 * candidate, or predating the `name` field, gets no export and is reported in `missingLocators`
 * instead of failing generation.
 */
export function generateLocatorModule(
  registry: SelectorRegistry,
  options: GenerateLocatorModuleOptions,
): GenerateLocatorModuleResult {
  const active = registry.elements.filter((element) => element.deprecatedAt === undefined);

  const missingLocators: MissingLocatorElement[] = active
    .filter((element) => !isGeneratable(element) || element.locatorCandidates.length === 0)
    .map((element) => ({ elementId: element.elementId, kind: element.kind }))
    .sort((a, b) => a.elementId.localeCompare(b.elementId));

  const generatable = active
    .filter((element): element is SelectorElement & { name: string } => isGeneratable(element))
    .filter((element) => element.locatorCandidates.length > 0)
    .slice()
    .sort(byName);

  const functions = generatable.map((element) => {
    const primary = element.locatorCandidates[0];
    if (primary === undefined) {
      throw new QaError(
        'explorer.locator_module.no_candidate',
        `element ${element.elementId} has no locator candidate`,
      );
    }
    return `export function ${element.name}(page: Page): Locator {\n  return ${locatorCall(primary)};\n}`;
  });

  const header = [
    '// Copyright The QA-AI-STLC Authors',
    '// SPDX-License-Identifier: Apache-2.0',
    '',
    `// Generated by @qa-ai-stlc/explorer@${options.generatorVersion} from the selector registry`,
    '// (ADR-006). Do not edit by hand; regenerate with `qa explore`.',
    '',
    "import type { Locator, Page } from 'playwright';",
    '',
    `export const GENERATOR_VERSION = ${JSON.stringify(options.generatorVersion)};`,
  ].join('\n');

  const source = `${[header, ...functions].join('\n\n')}\n`;

  return { source, missingLocators };
}
