// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { EngineContext } from './engine-context.js';
import { resolveRelativePath } from './paths.js';
import type { AxeRunPlan } from './operations/a11y-scan-plan.js';
import { toAxeContext } from './operations/a11y-scan-plan.js';

/** Where the generated helper lives, beside the locator module and the API auth helper. */
export const A11Y_SCAN_MODULE_PATH = 'tests/qa/a11y-scan.ts';

/**
 * The variable the `a11y` runner hands the scan plan to the spec process through. The engine sets
 * it on the child process only.
 */
export const A11Y_SCAN_ENVIRONMENT_VARIABLE = 'QA_A11Y_SCAN_PLAN';

/** Content type of the attachment the helper adds to a test: the raw axe-core result, classified later by the engine. */
export const A11Y_SCAN_ATTACHMENT_CONTENT_TYPE = 'application/vnd.qa-ai-stlc.axe-result+json';

const A11Y_SCAN_MODULE_VERSION = '1';

/**
 * Source of the helper a generated `a11y` spec imports to scan its page. The helper only runs
 * axe-core with the plan the engine resolved from `a11y` configuration and attaches the raw
 * result: which violations an exception covers, and what the result means for the case, is
 * decided by the engine afterwards, so no spec can quietly narrow its own scan.
 */
export function generateA11yScanModule(): string {
  return [
    '// Generated by QA-AI-STLC. Do not edit.',
    `export const GENERATOR_VERSION = '${A11Y_SCAN_MODULE_VERSION}';`,
    '',
    "import type { Page, TestInfo } from '@playwright/test';",
    '',
    '// Declared here so the helper typechecks without @types/node; it shadows the global where one exists.',
    'declare const process: { readonly env: Record<string, string | undefined> };',
    '',
    'interface ScanPlan {',
    '  readonly axePath: string;',
    '  readonly context?: unknown;',
    '  readonly options: unknown;',
    '}',
    '',
    '/** Scans the current page of `page` and attaches the raw axe-core result to the running test. */',
    'export async function scanAccessibility(page: Page, testInfo: TestInfo): Promise<void> {',
    `  const raw = process.env['${A11Y_SCAN_ENVIRONMENT_VARIABLE}'];`,
    '  if (raw === undefined) {',
    "    throw new Error('No accessibility scan plan was provided for this run; run the spec through `qa run --test-type a11y`.');",
    '  }',
    '  const plan = JSON.parse(raw) as ScanPlan;',
    '  await page.addScriptTag({ path: plan.axePath });',
    '  const result = await page.evaluate(',
    '    ({ context, options }) => {',
    '      const { axe, document } = globalThis as unknown as {',
    '        axe: { run: (...args: unknown[]) => Promise<unknown> };',
    '        document: unknown;',
    '      };',
    '      return axe.run(context ?? document, options);',
    '    },',
    '    { context: plan.context, options: plan.options },',
    '  );',
    `  await testInfo.attach('axe-result', { body: JSON.stringify(result), contentType: '${A11Y_SCAN_ATTACHMENT_CONTENT_TYPE}' });`,
    '}',
    '',
  ].join('\n');
}

/**
 * Writes the helper when it is missing or differs from what this version generates. Returns
 * whether it wrote, so callers can report a regeneration.
 */
export async function ensureA11yScanModule(
  context: EngineContext,
): Promise<{ readonly path: string; readonly didWrite: boolean }> {
  const absolutePath = resolveRelativePath(context.projectRoot, A11Y_SCAN_MODULE_PATH);
  const source = generateA11yScanModule();
  const isCurrent =
    (await context.fs.pathExists(absolutePath)) && (await context.fs.readFile(absolutePath)) === source;
  if (!isCurrent) {
    await context.fs.mkdir(dirname(absolutePath));
    await context.fs.writeFile(absolutePath, source);
  }
  return { path: A11Y_SCAN_MODULE_PATH, didWrite: !isCurrent };
}

/**
 * The browser script axe-core ships, as a path: Playwright's `addScriptTag({ path })` reads it
 * itself, which keeps the roughly 500 KB source out of an environment variable.
 */
export function resolveAxeSourcePath(): string {
  return fileURLToPath(import.meta.resolve('axe-core'));
}

/** The value of `A11Y_SCAN_ENVIRONMENT_VARIABLE`: what the helper passes to `axe.run`. */
export function serializeA11yScanPlan(plan: AxeRunPlan, axePath: string): string {
  const context = toAxeContext(plan);
  return JSON.stringify({
    axePath,
    ...(context === undefined ? {} : { context }),
    options: {
      runOnly: { type: 'tag', values: plan.tags },
      rules: Object.fromEntries(plan.ruleIds.map((ruleId) => [ruleId, { enabled: true }])),
    },
  });
}
