// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import type { ApiAuthConfig } from '@qa-ai-stlc/schemas';
import type { SensitiveNames } from './api-auth-redaction.js';
import { BUILT_IN_CREDENTIAL_HEADER_NAMES, type ResolvedApiAuth } from './api-auth.js';
import type { EngineContext } from './engine-context.js';
import { resolveRelativePath } from './paths.js';
import { dirname } from 'node:path';

/** Where the generated helper lives, beside the locator module (ADR-0006, ADR-0012). */
export const API_AUTH_MODULE_PATH = 'tests/qa/api-auth.ts';

/**
 * The variable the API runner hands the resolved credentials to the spec process through. The
 * engine sets it on the child process only; it is never written to disk (ADR-0012).
 */
export const API_AUTH_ENVIRONMENT_VARIABLE = 'QA_API_AUTH_RESOLVED';

const API_AUTH_MODULE_VERSION = '1';

/**
 * Source of the helper a generated API spec imports to authenticate. The spec names a profile
 * (`apiAuth('name')`); the helper looks the profile up in what the engine resolved for this run, so
 * no credential is ever in spec code. Profile names are a literal union, so a spec that names a
 * profile the configuration does not define fails typechecking instead of failing at run time.
 */
export function generateApiAuthModule(profileNames: readonly string[]): string {
  const nameUnion =
    profileNames.length === 0
      ? 'never'
      : [...profileNames]
          .sort()
          .map((name) => JSON.stringify(name))
          .join(' | ');
  return [
    '// Generated by QA-AI-STLC from the apiAuth profiles in .qa/config.yaml. Do not edit.',
    `export const GENERATOR_VERSION = '${API_AUTH_MODULE_VERSION}';`,
    '',
    '// Declared here so the helper typechecks without @types/node; it shadows the global where one exists.',
    'declare const process: { readonly env: Record<string, string | undefined> };',
    '',
    `export type ApiAuthProfileName = ${nameUnion};`,
    '',
    '/** Pass as the options of a Playwright `request` call: `request.get(url, apiAuth(profile))`. */',
    'export interface ApiAuthRequestOptions {',
    '  readonly headers: Record<string, string>;',
    '  readonly params: Record<string, string>;',
    '}',
    '',
    'export function apiAuth(profile: ApiAuthProfileName): ApiAuthRequestOptions {',
    `  const raw = process.env['${API_AUTH_ENVIRONMENT_VARIABLE}'];`,
    '  const resolved = raw === undefined ? undefined : (JSON.parse(raw) as Record<string, ApiAuthRequestOptions | undefined>)[profile];',
    '  if (resolved === undefined) {',
    '    throw new Error(`apiAuth profile "${profile}" was not resolved for this run`);',
    '  }',
    '  return resolved;',
    '}',
    '',
  ].join('\n');
}

/**
 * Writes the helper when it is missing or differs from what the configuration calls for. Returns
 * whether it wrote, so callers can report a regeneration.
 */
export async function ensureApiAuthModule(
  context: EngineContext,
  apiAuth: ApiAuthConfig,
): Promise<{ readonly path: string; readonly didWrite: boolean }> {
  const absolutePath = resolveRelativePath(context.projectRoot, API_AUTH_MODULE_PATH);
  const source = generateApiAuthModule(Object.keys(apiAuth.profiles));
  const isCurrent =
    (await context.fs.pathExists(absolutePath)) && (await context.fs.readFile(absolutePath)) === source;
  if (!isCurrent) {
    await context.fs.mkdir(dirname(absolutePath));
    await context.fs.writeFile(absolutePath, source);
  }
  return { path: API_AUTH_MODULE_PATH, didWrite: !isCurrent };
}

// A capture group is `string | undefined` to the compiler even when the pattern always fills it, so
// the undefined case is filtered out here once instead of at each use.
function capturedGroup(source: string, pattern: RegExp, groupIndex: number): string[] {
  return [...source.matchAll(pattern)]
    .map((match) => match[groupIndex])
    .filter((captured): captured is string => captured !== undefined);
}

const API_AUTH_CALL_PATTERN = /\bapiAuth\(\s*(['"])([^'"\\\r\n]+)\1\s*\)/gu;

/** The profile names a spec passes to `apiAuth('…')`, in first-use order and without repeats. */
export function extractSpecApiAuthProfiles(specSource: string): readonly string[] {
  return [...new Set(capturedGroup(specSource, API_AUTH_CALL_PATTERN, 2))];
}

/**
 * The `ResolvedApiAuth` set as the value of `API_AUTH_ENVIRONMENT_VARIABLE`: JSON keyed by profile
 * name, in the shape the generated helper hands to Playwright.
 */
export function serializeResolvedApiAuth(resolved: readonly ResolvedApiAuth[]): string {
  return JSON.stringify(
    Object.fromEntries(
      resolved.map((auth) => [auth.profileName, { headers: auth.headers, params: auth.queryParameters }]),
    ),
  );
}

const QUOTED_LITERAL_PATTERN = /(['"`])((?:(?!\1)[^\\\r\n]|\\.)*)\1/gu;
const INLINE_CREDENTIAL_PATTERN = /\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+/=-]{8,}/u;

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

/**
 * Describes the first place a spec's source carries a credential of its own instead of going
 * through a profile, or `undefined` when it carries none: a header or query-parameter name that
 * some profile uses (or `Authorization`/`Cookie`) written as a string or an object key, or a
 * `Bearer`/`Basic` value. This is a guard on the source the agent wrote, not proof that a spec is
 * credential-free; the run itself never gives a spec a credential except through the helper.
 */
export function findCredentialInSpecSource(specSource: string, names: SensitiveNames): string | undefined {
  const headerNames = new Set([
    ...BUILT_IN_CREDENTIAL_HEADER_NAMES,
    ...names.headers.map((name) => name.toLowerCase()),
  ]);
  const queryNames = names.queryParameters.map((name) => name.toLowerCase());

  for (const quoted of capturedGroup(specSource, QUOTED_LITERAL_PATTERN, 2)) {
    const literal = quoted.toLowerCase();
    if (headerNames.has(literal)) {
      return `the header name "${quoted}"`;
    }
    const queryName = queryNames.find((name) =>
      new RegExp(`(?:^|[?&])${escapeRegExp(name)}=`, 'u').test(literal),
    );
    if (queryName !== undefined) {
      return `the query parameter "${queryName}"`;
    }
  }
  for (const headerName of headerNames) {
    if (new RegExp(`(?<![\\w.'"\`-])${escapeRegExp(headerName)}\\s*:`, 'iu').test(specSource)) {
      return `the header name "${headerName}"`;
    }
  }
  return INLINE_CREDENTIAL_PATTERN.test(specSource) ? 'a Bearer or Basic credential value' : undefined;
}
