// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { SCHEMA_VERSION } from '@qa-ai-stlc/schemas';
import type { A11yConformanceLevel, A11yWcagVersion, TestingScope } from '@qa-ai-stlc/schemas';

/** The accessibility target the survey asks about when a11y testing is in scope. */
export interface A11yTargetAnswers {
  readonly wcagVersion: A11yWcagVersion;
  readonly level: A11yConformanceLevel;
  readonly bestPractices: boolean;
}

export const DEFAULT_A11Y_TARGET_ANSWERS: A11yTargetAnswers = {
  wcagVersion: '2.1',
  level: 'AA',
  bestPractices: false,
};

export interface RenderConfigYamlOptions {
  readonly testing: TestingScope;
  /** A local checkout of the application under test, for code-assisted checks and RCA context. */
  readonly sourcePath?: string;
  /** The OpenAPI contract source: a file/URL, or "discover"/"synthesize". Required when `testing.api` is `"in-scope"`. */
  readonly apiSource?: string;
  /** Written as an explicit `a11y` block; omitted, the schema defaults apply. */
  readonly a11y?: A11yTargetAnswers;
}

/**
 * Renders `config.yaml` for `qa init` (development plan section 3.3): the testing scope survey's
 * answers (P1-18), plus a safe starting point for everything else — `environments`/`identities`
 * start empty so the file validates against `ConfigSchema` before the operator has configured
 * anything.
 */
export function renderConfigYaml(options: RenderConfigYamlOptions): string {
  const sourceBlock =
    options.sourcePath === undefined ? '' : `\nsource:\n  path: ${JSON.stringify(options.sourcePath)}\n`;
  const apiBlock =
    options.apiSource === undefined
      ? ''
      : `\napi:\n  contract: openapi\n  source: ${JSON.stringify(options.apiSource)}\n`;

  // Version is quoted: an unquoted 2.1 is read back from YAML as a number.
  const a11yBlock =
    options.a11y === undefined
      ? ''
      : `
# Accessibility target: WCAG version, cumulative conformance level (AA covers A and AA), and
# whether axe-core best-practice rules run. Also supports include, exclude and exceptions
# (each with ruleId, reason and an optional expires date).
a11y:
  wcagVersion: "${options.a11y.wcagVersion}"
  level: ${options.a11y.level}
  bestPractices: ${String(options.a11y.bestPractices)}
`;

  return `# QA-AI-STLC project configuration. Generated by "qa init".
schemaVersion: ${String(SCHEMA_VERSION)}

# Web E2E, API, accessibility and security testing are decided independently. An "undecided"
# type blocks "qa scope" and every later phase until you change it here, with
# "qa config set testing.<type> in-scope|out-of-scope|undecided".
testing:
  e2e: ${options.testing.e2e}
  api: ${options.testing.api}
  a11y: ${options.testing.a11y}
  security: ${options.testing.security}
${sourceBlock}${apiBlock}${a11yBlock}
environments: {}

identities: {}

data:
  strategy: manual
  ownerMarker: qa-ai-stlc

selectors:
  policy: playwright-default
  testIdAttribute: data-testid

agents:
  parallelism: 1
  spokeTimeoutSeconds: 60
  retries: 1

flaky:
  historyWindow: 10
  minStatusChanges: 2
`;
}

export const LOCAL_LAYER_IGNORE_ENTRY = '/config.local.yaml';
export const CONFIG_LOCAL_EXAMPLE_PATH = 'config.local.yaml.example';

// Every line commented out: this file is never read by the loader (only the exact name
// "config.local.yaml", or the file QA_CONFIG_LOCAL names, is) and is committed for reference,
// unlike the real local layer itself, which "qa init" adds to .qa/.gitignore. Shows only the
// sections ADR-011 lets a local layer set (packages/schemas ConfigSchema's own classification).
export const CONFIG_LOCAL_EXAMPLE = `# Example local configuration layer (ADR-011).
#
# Copy the lines you need into ".qa/config.local.yaml" (git-ignored) or a file named by the
# QA_CONFIG_LOCAL environment variable. Only "environments", "identities", "source" and "agents"
# may be set here; every other section belongs in the committed ".qa/config.yaml". Every command
# that loads the configuration prints a warning for anything this layer makes less safe than the
# committed file, such as a widened allowlist or "tlsInsecure: true".
#
# environments:
#   staging:
#     baseUrl: https://staging.example.com
#     allowlist: [staging.example.com]
#     tlsInsecure: false
#     navigationTimeoutMs: 30000
#     actionTimeoutMs: 30000
#
# identities:
#   admin:
#     auth: cdp-attach
#     secret: QA_ADMIN_PASSWORD
#
# source:
#   path: ../app
#
# agents:
#   parallelism: 4
#   spokeTimeoutSeconds: 300
#   retries: 2
`;

// Runtime-only subdirectories (development plan section 3.2) and the machine-specific local
// configuration layer (ADR-011): everything else under `.qa/` is meant to be committed.
export const QA_GITIGNORE = `# Generated by "qa init".
/runs/
/evidence/
/auth/
/verifications/
${LOCAL_LAYER_IGNORE_ENTRY}
`;
