// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import {
  SCHEMA_VERSION,
  TestCaseSchema,
  type Approval,
  type GateState,
  type PhaseName,
  type PipelineState,
  type RelativePath,
  type TestingScope,
} from '@qa-ai-stlc/schemas';
import type { ApprovalLedgerStore } from './approval-ledger-store.js';
import { loadConfig } from './config-loader.js';
import { QaError } from './errors.js';
import { hashText } from './hash.js';
import type { ManifestStore } from './manifest-store.js';
import { PHASES } from './phases.js';
import { systemClock, type Clock } from './ports/clock.js';
import type { QaStore } from './qa-store.js';
import type { PipelineStateStore } from './state-store.js';
import { checkCaseSetCompleteness, findUndecidedTestingTypes } from './testing-scope.js';

export interface GateStateMachineOptions {
  readonly store: QaStore;
  readonly stateStore: PipelineStateStore;
  readonly ledger: ApprovalLedgerStore;
  readonly manifest: ManifestStore;
  readonly clock?: Clock;
}

export interface ApproveGateOptions {
  readonly gate: PhaseName;
  readonly artifactPath: RelativePath;
  readonly approvedBy: string;
  readonly note?: string;
}

const CASES_DIR: RelativePath = 'artifacts/cases/';

// The `cases` gate's canonical artifact (#357): a snapshot of every registered case file's path
// and content hash (`CasesIndexSchema`), regenerated by `qa cases add` after every case-set
// mutation. Binding to this aggregate, not to any one case file, is what makes approving `cases`
// approve the whole set — see `CANONICAL_ARTIFACT_BINDINGS` below.
export const CASES_INDEX_PATH: RelativePath = 'artifacts/cases-index.json';

function testingScopeMatches(a: TestingScope, b: TestingScope): boolean {
  return a.e2e === b.e2e && a.api === b.api && a.a11y === b.a11y && a.security === b.security;
}

interface CanonicalArtifactBinding {
  readonly path: RelativePath;
}

/**
 * What "the artifact for this gate" means (#305): each gate binds to exactly one file — `scope` to
 * the scope artifact, `cases` to the case-set aggregate at `CASES_INDEX_PATH` rather than to any
 * one case's own file (#357: a case is one of many files under `artifacts/cases/`, so binding to
 * one directly let editing any other case go undetected). Approving one gate can never bind to an
 * artifact that belongs to a different gate.
 */
const CANONICAL_ARTIFACT_BINDINGS: Record<PhaseName, CanonicalArtifactBinding> = {
  scope: { path: 'artifacts/scope.json' },
  cases: { path: CASES_INDEX_PATH },
};

function matchesCanonicalArtifactPath(gate: PhaseName, artifactPath: RelativePath): boolean {
  return artifactPath === CANONICAL_ARTIFACT_BINDINGS[gate].path;
}

function describeCanonicalArtifactPath(gate: PhaseName): string {
  return CANONICAL_ARTIFACT_BINDINGS[gate].path;
}

/**
 * The v0 pipeline state machine (development plan section 2.7, 8; ADR-003): `scope` then `cases`,
 * approved in order, each gate bound to the SHA-256 of the exact artifact content it approves.
 * `state.json` (`PipelineStateStore`) is always recomputed from the approval ledger and the
 * artifacts it references, never trusted as a cached status on its own — editing an approved
 * artifact reopens its gate the next time `approve()` or `validate()` runs, with no separate
 * tamper check required. `approve()` only ever binds to an artifact the engine itself registered
 * in the manifest (#278) — a path that merely exists cannot be approved — and only to the
 * artifact that actually belongs to the gate being approved (#305), not any other registered path.
 * A `cases` approval carrying a `testingScope` snapshot (P2-16) also reopens if the testing scope
 * config has since changed, the same recompute-not-cache treatment as the artifact hash itself.
 */
export class GateStateMachine {
  private readonly store: QaStore;
  private readonly stateStore: PipelineStateStore;
  private readonly ledger: ApprovalLedgerStore;
  private readonly manifest: ManifestStore;
  private readonly clock: Clock;

  constructor(options: GateStateMachineOptions) {
    this.store = options.store;
    this.stateStore = options.stateStore;
    this.ledger = options.ledger;
    this.manifest = options.manifest;
    this.clock = options.clock ?? systemClock;
  }

  /**
   * Hashes `artifactPath`'s current content and appends an approval for `gate` to the ledger.
   * Phases approve in order: approving a later phase while an earlier one is still open throws
   * `GATE_OUT_OF_ORDER`. Re-approving an already-satisfied gate is always allowed and simply
   * appends a new ledger entry, since the ledger is an audit trail, not a single current value.
   */
  async approve(options: ApproveGateOptions): Promise<PipelineState> {
    const state = await this.recomputeState();
    const gateIndex = PHASES.indexOf(options.gate);
    const currentIndex = PHASES.indexOf(state.currentPhase);
    if (gateIndex > currentIndex) {
      throw new QaError(
        'GATE_OUT_OF_ORDER',
        `Cannot approve "${options.gate}" before "${state.currentPhase}" is satisfied`,
        { remediation: `Approve phases in order: ${PHASES.join(' -> ')}.` },
      );
    }

    if (!matchesCanonicalArtifactPath(options.gate, options.artifactPath)) {
      throw new QaError(
        'GATE_ARTIFACT_PATH_MISMATCH',
        `"${options.artifactPath}" is not the artifact for the "${options.gate}" gate`,
        {
          remediation: `Approve "${options.gate}" with an artifact at ${describeCanonicalArtifactPath(options.gate)}.`,
        },
      );
    }

    const exists = await this.store.pathExists(options.artifactPath);
    if (!exists) {
      throw new QaError(
        'GATE_ARTIFACT_MISSING',
        `No artifact found at "${options.artifactPath}" to approve`,
        {
          remediation: 'Generate the artifact before approving its gate.',
        },
      );
    }
    const content = await this.store.readText(options.artifactPath);
    // A gate binds to what the engine actually wrote, not to whatever file happens to sit at this
    // path (#278) — an unregistered or hand-edited artifact throws ARTIFACT_UNREGISTERED /
    // ARTIFACT_HASH_MISMATCH here instead of being approved.
    await this.manifest.assertRegistered(options.artifactPath, content);

    // Testing-scope awareness (P2-16, development plan section 2.7) only applies to the `cases`
    // gate: `scope` approves regardless of which types are decided, since deciding them is what
    // `qa scope` itself already requires before it will even write an artifact to approve.
    const testingScope = options.gate === 'cases' ? await this.assertCaseSetReadyToApprove() : undefined;

    const approval: Approval = {
      gate: options.gate,
      artifactPath: options.artifactPath,
      artifactSha256: hashText(content),
      approvedBy: options.approvedBy,
      approvedAt: this.clock.now().toISOString(),
      ...(options.note !== undefined ? { note: options.note } : {}),
      ...(testingScope !== undefined ? { testingScope } : {}),
    };
    await this.ledger.append(approval);

    return this.recomputeState();
  }

  /**
   * Blocks approving `cases` while any testing-scope type is still `undecided`, or while it does
   * not yet have "one case set per in-scope type" (P2-16, development plan section 2.7): every
   * `in-scope` type needs at least one registered case, and no case may exist for a type that is
   * not `in-scope` (`checkCaseSetCompleteness`'s `not-applicable` never silently passes as done).
   * Returns the testing scope decided at this moment, to snapshot on the approval so a later
   * `qa config set` reopens the gate the same way editing the artifact itself does.
   */
  private async assertCaseSetReadyToApprove(): Promise<TestingScope> {
    const config = await loadConfig(this.store);
    const undecided = findUndecidedTestingTypes(config.testing);
    if (undecided.length > 0) {
      throw new QaError(
        'APPROVE_TESTING_UNDECIDED',
        `Testing scope is still undecided for: ${undecided.join(', ')}`,
        {
          remediation: 'Run "qa config set testing.<type> <in-scope|out-of-scope>" for each type listed.',
        },
      );
    }

    const casePaths = await this.store.listFiles(CASES_DIR);
    const cases = await Promise.all(casePaths.map((path) => this.store.readJson(path, TestCaseSchema)));
    const completeness = checkCaseSetCompleteness(config.testing, cases);
    const missingTypes = (
      Object.keys(completeness.statusByType) as (keyof typeof completeness.statusByType)[]
    )
      .filter((type) => completeness.statusByType[type] === 'missing')
      .sort();
    if (missingTypes.length > 0 || completeness.outOfScopeTypes.length > 0) {
      throw new QaError(
        'APPROVE_CASE_SET_INCOMPLETE',
        [
          missingTypes.length > 0
            ? `no case registered for in-scope type(s): ${missingTypes.join(', ')}`
            : null,
          completeness.outOfScopeTypes.length > 0
            ? `case(s) registered for non-in-scope type(s): ${completeness.outOfScopeTypes.join(', ')}`
            : null,
        ]
          .filter((line) => line !== null)
          .join('; '),
        {
          remediation:
            'Register a case for every in-scope type with "qa cases add", and remove or re-type any case whose type is not in scope.',
        },
      );
    }

    return config.testing;
  }

  /**
   * Recomputes every gate's status from the approval ledger and each approved artifact's current
   * content, persists the refreshed `state.json`, and returns it. Reports no more and no less
   * than `approve()` already recomputes after every call — the two share this method so there is
   * one place, not two, that decides what "satisfied" means.
   */
  async validate(): Promise<PipelineState> {
    return this.recomputeState();
  }

  private async recomputeState(): Promise<PipelineState> {
    const gates = {} as Record<PhaseName, GateState>;
    for (const phase of PHASES) {
      gates[phase] = await this.recomputeGate(phase);
    }

    // The first not-yet-satisfied phase in order; if every phase is satisfied, the loop runs to
    // the end without breaking and `currentPhase` is left at the last one — v0 has nothing after
    // it yet, so it stays "current" rather than needing a distinct "done" phase.
    let currentPhase: PhaseName = PHASES[0];
    for (const phase of PHASES) {
      currentPhase = phase;
      if (gates[phase].status !== 'satisfied') {
        break;
      }
    }

    const state: PipelineState = { schemaVersion: SCHEMA_VERSION, currentPhase, gates };
    await this.stateStore.save(state);
    return state;
  }

  private async recomputeGate(phase: PhaseName): Promise<GateState> {
    const approval = await this.ledger.latestForGate(phase);
    if (approval === undefined) {
      return { status: 'open' };
    }
    const artifactExists = await this.store.pathExists(approval.artifactPath);
    /* v8 ignore next 3 -- FileSystem (ports/file-system.ts) has no delete operation, so a
       registered artifact disappearing between approval and validation cannot be constructed by a
       test today; kept so a manually deleted file reads as a reopened gate, not a thrown ENOENT. */
    if (!artifactExists) {
      return { status: 'open' };
    }
    const content = await this.store.readText(approval.artifactPath);
    if (hashText(content) !== approval.artifactSha256) {
      return { status: 'open' };
    }
    if (approval.testingScope === undefined) {
      return { status: 'satisfied' };
    }
    // A scope decision (P2-16) changed since this gate was approved reopens it even though the
    // approved artifact's own content never changed — `qa config set testing.<type>` has no other
    // effect on the ledger or the artifact itself, so this is the only place that catches it.
    const config = await loadConfig(this.store);
    return { status: testingScopeMatches(approval.testingScope, config.testing) ? 'satisfied' : 'open' };
  }
}
