// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import type { WcagCriterion } from './types.js';

export const OPERABLE_CRITERIA: readonly WcagCriterion[] = [
  {
    id: '2.1.1',
    name: 'Everything works from the keyboard',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['frame-focusable-content', 'scrollable-region-focusable', 'server-side-image-map'],
    manualCheck:
      'Every function, including custom widgets, drag and drop and hover-only actions, can be operated with the keyboard alone.',
  },
  {
    id: '2.1.2',
    name: 'No keyboard trap',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Focus can always be moved away from every component using the keyboard, including dialogs, embedded content and editors.',
  },
  {
    id: '2.1.3',
    name: 'Keyboard only, without exceptions',
    level: 'AAA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['scrollable-region-focusable'],
    manualCheck:
      'Every function is keyboard operable with no exception for path-dependent input such as freehand drawing.',
  },
  {
    id: '2.1.4',
    name: 'Single-key shortcuts controllable',
    level: 'A',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'A shortcut made of a single printable character can be turned off, remapped, or only fires while its component has focus.',
  },
  {
    id: '2.2.1',
    name: 'Adjustable time limits',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['meta-refresh'],
    manualCheck:
      'A session timeout or timed action can be turned off, adjusted or extended, unless the limit is essential.',
  },
  {
    id: '2.2.2',
    name: 'Pause moving or updating content',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['blink', 'marquee'],
    manualCheck:
      'Carousels, animations, tickers and auto-updating content that run over five seconds can be paused, stopped or hidden.',
  },
  {
    id: '2.2.3',
    name: 'No timing',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Timing is not an essential part of any activity, apart from real-time events.',
  },
  {
    id: '2.2.4',
    name: 'Interruptions postponed',
    level: 'AAA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['meta-refresh-no-exceptions'],
    manualCheck:
      'The user can postpone or suppress interruptions such as update notices, except emergencies.',
  },
  {
    id: '2.2.5',
    name: 'Re-authenticating without data loss',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'After a session expires and the user signs in again, the earlier activity continues without data loss.',
  },
  {
    id: '2.2.6',
    name: 'Timeout warnings',
    level: 'AAA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Users are warned about inactivity timeouts that would lose data, unless the data is kept for over 20 hours.',
  },
  {
    id: '2.3.1',
    name: 'No more than three flashes',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Nothing flashes more than three times in any one second, or the flash stays below the general and red flash thresholds.',
  },
  {
    id: '2.3.2',
    name: 'No flashing at all',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Nothing flashes more than three times in any one second.',
  },
  {
    id: '2.3.3',
    name: 'Motion animation can be disabled',
    level: 'AAA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Animation triggered by interaction can be turned off, unless it is essential; the reduced-motion preference is honoured.',
  },
  {
    id: '2.4.1',
    name: 'Skip repeated blocks',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['bypass'],
    manualCheck:
      'A working skip link, landmarks or headings let keyboard users bypass repeated navigation and reach the main content.',
  },
  {
    id: '2.4.2',
    name: 'Descriptive page title',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['document-title'],
    manualCheck: 'Each page title describes its topic or purpose and differs between pages.',
  },
  {
    id: '2.4.3',
    name: 'Logical focus order',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Tabbing follows an order that preserves meaning and operability, including after dialogs open and close.',
  },
  {
    id: '2.4.4',
    name: 'Link purpose from context',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['area-alt', 'link-name'],
    manualCheck:
      'The purpose of each link is clear from its text or its surrounding context, not only that it has a name.',
  },
  {
    id: '2.4.5',
    name: 'More than one way to find pages',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Pages in a set can be reached in at least two ways, such as navigation, search or a site map.',
  },
  {
    id: '2.4.6',
    name: 'Descriptive headings and labels',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Headings and form labels describe the topic or purpose of what follows.',
  },
  {
    id: '2.4.7',
    name: 'Visible focus indicator',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Every keyboard-focusable element shows a visible focus indicator.',
  },
  {
    id: '2.4.8',
    name: 'Location within the site',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Users can tell where the current page sits within the site, for example via breadcrumbs.',
  },
  {
    id: '2.4.9',
    name: 'Link purpose from text alone',
    level: 'AAA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['identical-links-same-purpose'],
    manualCheck: 'Each link makes its purpose clear from the link text alone.',
  },
  {
    id: '2.4.10',
    name: 'Section headings',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Content is divided into sections that each have a heading.',
  },
  {
    id: '2.4.11',
    name: 'Focused element not hidden',
    level: 'AA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'A focused element is never completely hidden by sticky headers, footers or overlays.',
  },
  {
    id: '2.4.12',
    name: 'Focused element fully visible',
    level: 'AAA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'No part of a focused element is hidden by author-created content.',
  },
  {
    id: '2.4.13',
    name: 'Focus indicator appearance',
    level: 'AAA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'The focus indicator is large enough, has enough contrast, and differs clearly from the unfocused state.',
  },
  {
    id: '2.5.1',
    name: 'Alternatives to path gestures',
    level: 'A',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Functions that need multipoint or path-based gestures can also be done with a single-pointer action.',
  },
  {
    id: '2.5.2',
    name: 'Pointer actions can be cancelled',
    level: 'A',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'A single-pointer action fires on release, and can be aborted or undone, rather than on the initial press.',
  },
  {
    id: '2.5.3',
    name: 'Visible label in accessible name',
    level: 'A',
    since: '2.1',
    coverage: 'partial',
    axeRuleIds: ['label-content-name-mismatch'],
    manualCheck: 'The accessible name of every control that shows a text label contains that visible text.',
  },
  {
    id: '2.5.4',
    name: 'Motion actuation alternatives',
    level: 'A',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Functions triggered by device or user motion also have a control, and the motion trigger can be disabled.',
  },
  {
    id: '2.5.5',
    name: 'Large target size',
    level: 'AAA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Pointer targets are at least 44 by 44 CSS pixels, unless an exception applies.',
  },
  {
    id: '2.5.6',
    name: 'Concurrent input mechanisms',
    level: 'AAA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'The page does not restrict use to one input type such as touch only or mouse only.',
  },
  {
    id: '2.5.7',
    name: 'Dragging has an alternative',
    level: 'AA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Every drag action can also be done with a single pointer without dragging.',
  },
  {
    id: '2.5.8',
    name: 'Minimum target size',
    level: 'AA',
    since: '2.2',
    coverage: 'partial',
    axeRuleIds: ['target-size'],
    manualCheck:
      'Pointer targets are at least 24 by 24 CSS pixels or have enough spacing; inline links and user-agent controls are exempt.',
  },
];
