// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import type { WcagCriterion } from './types.js';

export const PERCEIVABLE_CRITERIA: readonly WcagCriterion[] = [
  {
    id: '1.1.1',
    name: 'Text alternatives',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: [
      'aria-meter-name',
      'aria-progressbar-name',
      'image-alt',
      'input-image-alt',
      'object-alt',
      'role-img-alt',
      'svg-img-alt',
    ],
    manualCheck:
      'Each informative image, icon and control image has an alternative that conveys the same purpose; decorative ones are hidden from assistive technology.',
  },
  {
    id: '1.2.1',
    name: 'Audio-only and video-only alternatives',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Prerecorded audio-only content has a transcript; prerecorded video-only content has a transcript or an audio description.',
  },
  {
    id: '1.2.2',
    name: 'Captions for recorded video',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['video-caption'],
    manualCheck:
      'Captions exist for every prerecorded video with sound and match the speech and relevant sounds.',
  },
  {
    id: '1.2.3',
    name: 'Audio description or transcript',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Prerecorded video has an audio description or a full text alternative for what is shown.',
  },
  {
    id: '1.2.4',
    name: 'Captions for live media',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Live video with sound is captioned in real time.',
  },
  {
    id: '1.2.5',
    name: 'Audio description for recorded video',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Prerecorded video has an audio description track.',
  },
  {
    id: '1.2.6',
    name: 'Sign language',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Prerecorded video with sound offers a sign language interpretation.',
  },
  {
    id: '1.2.7',
    name: 'Extended audio description',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Where pauses are too short for audio description, the video pauses or an extended description is offered.',
  },
  {
    id: '1.2.8',
    name: 'Full text alternative for media',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Prerecorded synchronized media and video-only content has a full text alternative.',
  },
  {
    id: '1.2.9',
    name: 'Live audio-only alternative',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Live audio-only content has a text alternative.',
  },
  {
    id: '1.3.1',
    name: 'Structure conveyed in markup',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: [
      'aria-hidden-body',
      'aria-required-children',
      'aria-required-parent',
      'definition-list',
      'dlitem',
      'list',
      'listitem',
      'p-as-heading',
      'table-fake-caption',
      'td-has-header',
      'td-headers-attr',
      'th-has-data-cells',
    ],
    manualCheck:
      'Headings, lists, tables, form groups and landmarks reflect the visual structure and are marked up as such, not only styled to look that way.',
  },
  {
    id: '1.3.2',
    name: 'Meaningful reading order',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'With styles disabled or read linearly, the content order still makes sense.',
  },
  {
    id: '1.3.3',
    name: 'Instructions not tied to sensory traits',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Instructions do not rely only on shape, colour, size, position or sound to identify something.',
  },
  {
    id: '1.3.4',
    name: 'Orientation not locked',
    level: 'AA',
    since: '2.1',
    coverage: 'partial',
    axeRuleIds: ['css-orientation-lock'],
    manualCheck:
      'The page works in both portrait and landscape unless one orientation is essential; check script-based locks too.',
  },
  {
    id: '1.3.5',
    name: 'Input purpose identified',
    level: 'AA',
    since: '2.1',
    coverage: 'partial',
    axeRuleIds: ['autocomplete-valid'],
    manualCheck:
      'Every field that collects personal data about the user carries the matching autocomplete purpose.',
  },
  {
    id: '1.3.6',
    name: 'Purpose of components identified',
    level: 'AAA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'The purpose of controls, icons and regions can be determined programmatically.',
  },
  {
    id: '1.4.1',
    name: 'Colour is not the only cue',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['link-in-text-block'],
    manualCheck:
      'Errors, required fields, states and chart series are distinguishable without relying on colour alone.',
  },
  {
    id: '1.4.2',
    name: 'Audio control',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['no-autoplay-audio'],
    manualCheck:
      'Audio that starts automatically and lasts over three seconds can be paused, stopped or muted.',
  },
  {
    id: '1.4.3',
    name: 'Text contrast',
    level: 'AA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['color-contrast'],
    manualCheck:
      'Text over images, gradients and other backgrounds the scan could not evaluate meets the required contrast ratio.',
  },
  {
    id: '1.4.4',
    name: 'Text resizes to 200 percent',
    level: 'AA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['meta-viewport'],
    manualCheck:
      'At 200 percent text zoom, nothing is cut off, overlapped or lost, and no horizontal scrolling is needed for a line of text.',
  },
  {
    id: '1.4.5',
    name: 'Real text instead of images of text',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Text is rendered as text, not as an image, unless the image is essential.',
  },
  {
    id: '1.4.6',
    name: 'Enhanced text contrast',
    level: 'AAA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['color-contrast-enhanced'],
    manualCheck:
      'Text over images, gradients and other backgrounds the scan could not evaluate meets the enhanced contrast ratio.',
  },
  {
    id: '1.4.7',
    name: 'Low or no background audio',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Speech recordings have no background sound, or it can be turned off or is much quieter.',
  },
  {
    id: '1.4.8',
    name: 'Visual presentation of text blocks',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Blocks of text let the reader choose colours, keep lines short, avoid justification, allow generous spacing and resize without horizontal scrolling.',
  },
  {
    id: '1.4.9',
    name: 'No images of text',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Images of text are used only for decoration or where a particular look is essential.',
  },
  {
    id: '1.4.10',
    name: 'Reflow at narrow widths',
    level: 'AA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'At 320 CSS pixels wide (or 256 high for horizontal scrolling content), content reflows without two-dimensional scrolling or lost information.',
  },
  {
    id: '1.4.11',
    name: 'Contrast of controls and graphics',
    level: 'AA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Control boundaries, focus and state indicators, and meaningful graphics reach a 3:1 contrast against their surroundings.',
  },
  {
    id: '1.4.12',
    name: 'Text spacing adjustable',
    level: 'AA',
    since: '2.1',
    coverage: 'partial',
    axeRuleIds: ['avoid-inline-spacing'],
    manualCheck:
      'With the line, paragraph, letter and word spacing raised to the required values, no content is lost or overlaps.',
  },
  {
    id: '1.4.13',
    name: 'Hover and focus content',
    level: 'AA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Content shown on hover or focus can be dismissed without moving the pointer, stays while hovered, and stays until dismissed.',
  },
];
