// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import type { WcagCriterion } from './types.js';

export const UNDERSTANDABLE_ROBUST_CRITERIA: readonly WcagCriterion[] = [
  {
    id: '3.1.1',
    name: 'Page language declared',
    level: 'A',
    since: '2.0',
    coverage: 'automated',
    axeRuleIds: ['html-has-lang', 'html-lang-valid', 'html-xml-lang-mismatch'],
  },
  {
    id: '3.1.2',
    name: 'Language of parts',
    level: 'AA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['valid-lang'],
    manualCheck: 'Passages in a language other than the page language are marked with the correct language.',
  },
  {
    id: '3.1.3',
    name: 'Unusual words explained',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Idioms, jargon and other unusual words have a definition mechanism.',
  },
  {
    id: '3.1.4',
    name: 'Abbreviations explained',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'A way exists to find the expanded form or meaning of abbreviations.',
  },
  {
    id: '3.1.5',
    name: 'Reading level',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Text needing more than lower-secondary reading ability has a simpler version or supplement.',
  },
  {
    id: '3.1.6',
    name: 'Pronunciation',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Words whose meaning depends on pronunciation have a way to find it.',
  },
  {
    id: '3.2.1',
    name: 'No context change on focus',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Moving focus to a component does not by itself navigate or change the context.',
  },
  {
    id: '3.2.2',
    name: 'No context change on input',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Changing a field value does not trigger a context change unless the user was told first.',
  },
  {
    id: '3.2.3',
    name: 'Consistent navigation',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Repeated navigation appears in the same relative order across pages.',
  },
  {
    id: '3.2.4',
    name: 'Consistent identification',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Components with the same function are labelled the same way across pages.',
  },
  {
    id: '3.2.5',
    name: 'Changes only on request',
    level: 'AAA',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['meta-refresh-no-exceptions'],
    manualCheck:
      'Context changes such as pop-ups or focus moves happen only on user request or can be turned off.',
  },
  {
    id: '3.2.6',
    name: 'Consistent help placement',
    level: 'A',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Help mechanisms such as contact details, chat or a help link sit in the same relative place across pages.',
  },
  {
    id: '3.3.1',
    name: 'Errors identified in text',
    level: 'A',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Input errors are detected automatically, and the field in error is identified and described in text.',
  },
  {
    id: '3.3.2',
    name: 'Labels or instructions',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: ['form-field-multiple-labels'],
    manualCheck:
      'Every input has a visible label or instruction that says what is expected, including format and required state.',
  },
  {
    id: '3.3.3',
    name: 'Error suggestions',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'When a correction is known, the error message suggests it.',
  },
  {
    id: '3.3.4',
    name: 'Error prevention for important data',
    level: 'AA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Legal, financial and data-changing submissions can be reversed, checked or confirmed before they complete.',
  },
  {
    id: '3.3.5',
    name: 'Contextual help',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Context-sensitive help is available where the user enters data.',
  },
  {
    id: '3.3.6',
    name: 'Error prevention for all submissions',
    level: 'AAA',
    since: '2.0',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck: 'Every submission can be reversed, checked or confirmed.',
  },
  {
    id: '3.3.7',
    name: 'No repeated data entry',
    level: 'A',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Information already entered in the same process is prefilled or selectable, unless re-entry is essential.',
  },
  {
    id: '3.3.8',
    name: 'Accessible authentication',
    level: 'AA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Signing in does not depend on remembering, transcribing or solving a puzzle; pasting and password managers work.',
  },
  {
    id: '3.3.9',
    name: 'Accessible authentication without exceptions',
    level: 'AAA',
    since: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Signing in never depends on a cognitive function test, including object or image recognition.',
  },
  {
    id: '4.1.1',
    name: 'Well-formed markup',
    level: 'A',
    since: '2.0',
    removedIn: '2.2',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Run a markup validator: elements are properly opened and closed, attributes are not duplicated and ids are unique.',
  },
  {
    id: '4.1.2',
    name: 'Name, role and value exposed',
    level: 'A',
    since: '2.0',
    coverage: 'partial',
    axeRuleIds: [
      'area-alt',
      'aria-allowed-attr',
      'aria-braille-equivalent',
      'aria-command-name',
      'aria-conditional-attr',
      'aria-deprecated-role',
      'aria-hidden-body',
      'aria-hidden-focus',
      'aria-input-field-name',
      'aria-prohibited-attr',
      'aria-required-attr',
      'aria-roles',
      'aria-tab-name',
      'aria-toggle-field-name',
      'aria-tooltip-name',
      'aria-valid-attr',
      'aria-valid-attr-value',
      'button-name',
      'duplicate-id-aria',
      'frame-title',
      'frame-title-unique',
      'input-button-name',
      'input-image-alt',
      'label',
      'link-name',
      'nested-interactive',
      'select-name',
      'summary-name',
    ],
    manualCheck:
      'Custom widgets expose the right role, an accessible name and their current state and value to assistive technology, and state changes are announced.',
  },
  {
    id: '4.1.3',
    name: 'Status messages announced',
    level: 'AA',
    since: '2.1',
    coverage: 'manual',
    axeRuleIds: [],
    manualCheck:
      'Status messages such as success, error and progress are announced by assistive technology without receiving focus.',
  },
];
