// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { join } from 'node:path';
import { QaError } from '../errors.js';
import { SCHEMA_VERSION, type TestCase } from '@qa-ai-stlc/schemas';
import { describe, expect, it } from 'vitest';
import type { EngineContext } from '../engine-context.js';
import { createFakeEngineContext } from '../test-support/fake-engine-context.js';
import { runBuildGenerationSpokeInput } from './generation-spoke-input.js';
import { createFakeFileSystem, type FakeFileSystem } from '@qa-ai-stlc/test-utils/fake-file-system';

const NOW = new Date('2026-09-27T10:00:00.000Z');
const TEST_CASE: TestCase = {
  schemaVersion: SCHEMA_VERSION,
  id: 'checkout-guest',
  feature: 'checkout',
  requirementIds: ['req-1'],
  testType: 'e2e',
  title: 'A guest can check out',
  steps: [{ description: 'Add an item to the cart' }],
  expectedResult: 'The order confirmation page is shown',
  status: 'approved',
  createdAt: '2026-09-25T09:00:00.000Z',
};

const LOCATOR_MODULE_SOURCE = [
  '// Generated by @qa-ai-stlc/explorer@1.3.0 from the selector registry',
  'export const GENERATOR_VERSION = "1.3.0";',
  '',
].join('\n');

function createContext(): { readonly context: EngineContext; readonly fs: FakeFileSystem } {
  const fs = createFakeFileSystem();
  return { context: createFakeEngineContext({ fs, clock: { now: () => NOW } }), fs };
}

async function seedCase(fs: FakeFileSystem): Promise<void> {
  await fs.mkdir(join('project', '.qa', 'artifacts', 'cases', 'checkout'));
  await fs.writeFile(
    join('project', '.qa', 'artifacts', 'cases', 'checkout', `${TEST_CASE.id}.json`),
    JSON.stringify(TEST_CASE),
  );
}

async function seedLocatorModule(fs: FakeFileSystem, source: string = LOCATOR_MODULE_SOURCE): Promise<void> {
  await fs.mkdir(join('project', 'tests', 'qa'));
  await fs.writeFile(join('project', 'tests', 'qa', 'locators.ts'), source);
}

async function seedRegistry(fs: FakeFileSystem): Promise<void> {
  await fs.mkdir(join('project', '.qa', 'selectors'));
  await fs.writeFile(
    join('project', '.qa', 'selectors', 'registry.json'),
    JSON.stringify({
      schemaVersion: SCHEMA_VERSION,
      generatedAt: '2026-09-25T09:00:00.000Z',
      elements: [
        {
          elementId: 'el-1',
          name: 'checkoutButton',
          kind: 'button',
          locatorCandidates: [{ strategy: 'testId', value: 'checkout-button', fragile: false }],
          stabilityScore: 1,
          lastVerifiedAt: '2026-09-25T09:00:00.000Z',
          source: 'crawl',
        },
      ],
    }),
  );
}

describe('runBuildGenerationSpokeInput', () => {
  it('assembles the spoke input from the registered case, registry slice and real generator version', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedRegistry(fs);
    await seedLocatorModule(fs);

    const input = await runBuildGenerationSpokeInput(context, {
      testCaseId: TEST_CASE.id,
      elementIds: ['el-1'],
    });

    expect(input.testCase).toEqual(TEST_CASE);
    expect(input.registrySlice?.elements.map((element) => element.elementId)).toEqual(['el-1']);
    expect(input.locatorModule).toEqual({
      generatorVersion: '1.3.0',
      exports: [{ elementId: 'el-1', name: 'checkoutButton' }],
    });
    expect(input.provenSession).toBeUndefined();
  });

  it('passes a given provenSession through unchanged', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedLocatorModule(fs);
    const provenSession = {
      schemaVersion: SCHEMA_VERSION as 1,
      testCaseId: TEST_CASE.id,
      runResultId: 'run-result-1',
      steps: [
        {
          stepId: 'step-1',
          description: 'Add an item to the cart',
          actions: [
            {
              schemaVersion: SCHEMA_VERSION as 1,
              type: 'click' as const,
              sessionId: 'session-1',
              stepId: 'step-1',
              at: '2026-09-25T09:59:30.000Z',
            },
          ],
        },
      ],
    };

    const input = await runBuildGenerationSpokeInput(context, {
      testCaseId: TEST_CASE.id,
      elementIds: [],
      provenSession,
    });

    expect(input.provenSession).toEqual(provenSession);
  });

  it('falls back to an empty registry when none is registered yet', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedLocatorModule(fs);

    const input = await runBuildGenerationSpokeInput(context, { testCaseId: TEST_CASE.id, elementIds: [] });

    expect(input.registrySlice?.elements).toEqual([]);
  });

  it('throws when an elementId does not resolve in the registry', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedRegistry(fs);
    await seedLocatorModule(fs);

    await expect(
      runBuildGenerationSpokeInput(context, { testCaseId: TEST_CASE.id, elementIds: ['no-such-element'] }),
    ).rejects.toBeInstanceOf(QaError);
  });

  it('throws when the locator module has not been generated yet', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);

    const error = await runBuildGenerationSpokeInput(context, {
      testCaseId: TEST_CASE.id,
      elementIds: [],
    }).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(QaError);
    expect((error as QaError).code).toBe('GENERATION_LOCATOR_MODULE_MISSING');
  });

  it('throws when the locator module has no GENERATOR_VERSION export', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedLocatorModule(fs, '// no generator version stamp\n');

    const error = await runBuildGenerationSpokeInput(context, {
      testCaseId: TEST_CASE.id,
      elementIds: [],
    }).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(QaError);
    expect((error as QaError).code).toBe('GENERATION_LOCATOR_MODULE_VERSION_MISSING');
  });

  it('throws when the GENERATOR_VERSION export has no closing quote', async () => {
    const { context, fs } = createContext();
    await seedCase(fs);
    await seedLocatorModule(fs, 'export const GENERATOR_VERSION = "1.3.0;\n');

    const error = await runBuildGenerationSpokeInput(context, {
      testCaseId: TEST_CASE.id,
      elementIds: [],
    }).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(QaError);
    expect((error as QaError).code).toBe('GENERATION_LOCATOR_MODULE_VERSION_MISSING');
  });
});

describe('runBuildGenerationSpokeInput for an api case (P6-13)', () => {
  const CONTRACT = JSON.stringify({
    openapi: '3.0.3',
    paths: { '/tasks/{taskId}': { get: { operationId: 'getTask' } } },
  });
  const CONFIG_YAML = [
    'schemaVersion: 1',
    'testing: { e2e: undecided, api: in-scope, a11y: undecided, security: undecided }',
    'environments:\n  staging: { baseUrl: "https://staging.example.test", allowlist: ["staging.example.test"] }',
    'identities: {}',
    'data: { strategy: manual, ownerMarker: qa-ai-stlc }',
    'selectors: { policy: playwright-default, testIdAttribute: data-testid }',
    'agents: { parallelism: 1, spokeTimeoutSeconds: 60, retries: 1 }',
    'api: { contract: openapi, source: openapi.json }',
    '',
  ].join('\n');

  async function seedApiProject(fs: FakeFileSystem, endpoints: TestCase['endpoints']): Promise<void> {
    await fs.mkdir(join('project', '.qa', 'artifacts', 'cases', 'tasks'));
    await fs.writeFile(
      join('project', '.qa', 'artifacts', 'cases', 'tasks', 'api-case.json'),
      JSON.stringify({
        ...TEST_CASE,
        id: 'api-case',
        feature: 'tasks',
        testType: 'api',
        ...(endpoints === undefined ? {} : { endpoints }),
      }),
    );
    await fs.writeFile(join('project', '.qa', 'config.yaml'), CONFIG_YAML);
    await fs.writeFile(join('project', 'openapi.json'), CONTRACT);
  }

  it('builds the input from the contract, needing neither a registry nor a locator module', async () => {
    const { context, fs } = createContext();
    await seedApiProject(fs, [{ method: 'GET', path: '/tasks/{id}' }]);

    const input = await runBuildGenerationSpokeInput(context, { testCaseId: 'api-case', elementIds: [] });

    expect(input.registrySlice).toBeUndefined();
    expect(input.locatorModule).toBeUndefined();
    expect(input.apiContract?.source).toBe('openapi.json');
    expect(input.apiContract?.operations.map((operation) => operation.path)).toEqual(['/tasks/{taskId}']);
  });

  it('passes a proven session and the environment name through', async () => {
    const { context, fs } = createContext();
    await seedApiProject(fs, [{ method: 'GET', path: '/tasks/{id}' }]);
    const provenSession = {
      schemaVersion: SCHEMA_VERSION as 1,
      testCaseId: 'api-case',
      runResultId: 'run-result-1',
      steps: [
        {
          stepId: 'step-1',
          description: 'call it',
          actions: [
            {
              schemaVersion: SCHEMA_VERSION as 1,
              type: 'click' as const,
              sessionId: 'session-1',
              stepId: 'step-1',
              at: '2026-09-25T09:59:30.000Z',
            },
          ],
        },
      ],
    };

    const input = await runBuildGenerationSpokeInput(context, {
      testCaseId: 'api-case',
      elementIds: [],
      environment: 'staging',
      provenSession,
    });

    expect(input.provenSession).toEqual(provenSession);
  });

  it('rejects an api case that lists no endpoints', async () => {
    const { context, fs } = createContext();
    await seedApiProject(fs, undefined);

    const rejected = await runBuildGenerationSpokeInput(context, {
      testCaseId: 'api-case',
      elementIds: [],
    }).catch((caught: unknown) => caught);

    expect(rejected).toMatchObject({ code: 'API_CASE_INVALID' });
  });

  it('rejects an api case naming an operation the contract lacks', async () => {
    const { context, fs } = createContext();
    await seedApiProject(fs, [{ method: 'DELETE', path: '/tasks/{id}' }]);

    const rejected = await runBuildGenerationSpokeInput(context, {
      testCaseId: 'api-case',
      elementIds: [],
    }).catch((caught: unknown) => caught);

    expect(rejected).toMatchObject({ code: 'API_CASE_NOT_IN_CONTRACT' });
  });
});
