// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { SCHEMA_VERSION } from '@qa-ai-stlc/schemas';

// A safe starting point every "qa init" writes: every testing type starts "undecided" (the
// testing-scope survey that turns these into real decisions is P1-18), and `environments` /
// `identities` start empty so the file validates against `ConfigSchema` before the operator has
// configured anything (development plan section 3.2, 3.3).
export const CONFIG_TEMPLATE = `# QA-AI-STLC project configuration. Generated by "qa init".
schemaVersion: ${String(SCHEMA_VERSION)}

# Web E2E, API, accessibility and security testing are decided independently. An "undecided"
# type blocks "qa scope" and every later phase until you change it here.
testing:
  e2e: undecided
  api: undecided
  a11y: undecided
  security: undecided

environments: {}

identities: {}

data:
  strategy: manual
  ownerMarker: qa-ai-stlc

selectors:
  policy: playwright-default
  testIdAttribute: data-testid

agents:
  parallelism: 1
  spokeTimeoutSeconds: 60
  retries: 1
`;

// Runtime-only subdirectories (development plan section 3.2): everything else under `.qa/` is
// meant to be committed.
export const QA_GITIGNORE = `# Generated by "qa init".
/runs/
/evidence/
/auth/
`;
