// Copyright The QA-AI-STLC Authors
// SPDX-License-Identifier: Apache-2.0

import { SCHEMA_VERSION } from '@qa-ai-stlc/schemas';
import type { TestingScope } from '@qa-ai-stlc/schemas';

export interface RenderConfigYamlOptions {
  readonly testing: TestingScope;
  /** A local checkout of the application under test, for code-assisted checks and RCA context. */
  readonly sourcePath?: string;
  /** The OpenAPI contract source: a file/URL, or "discover"/"synthesize". Required when `testing.api` is `"in-scope"`. */
  readonly apiSource?: string;
}

/**
 * Renders `config.yaml` for `qa init` (development plan section 3.3): the testing scope survey's
 * answers (P1-18), plus a safe starting point for everything else — `environments`/`identities`
 * start empty so the file validates against `ConfigSchema` before the operator has configured
 * anything.
 */
export function renderConfigYaml(options: RenderConfigYamlOptions): string {
  const sourceBlock =
    options.sourcePath === undefined ? '' : `\nsource:\n  path: ${JSON.stringify(options.sourcePath)}\n`;
  const apiBlock =
    options.apiSource === undefined
      ? ''
      : `\napi:\n  contract: openapi\n  source: ${JSON.stringify(options.apiSource)}\n`;

  return `# QA-AI-STLC project configuration. Generated by "qa init".
schemaVersion: ${String(SCHEMA_VERSION)}

# Web E2E, API, accessibility and security testing are decided independently. An "undecided"
# type blocks "qa scope" and every later phase until you change it here, with
# "qa config set testing.<type> in-scope|out-of-scope|undecided".
testing:
  e2e: ${options.testing.e2e}
  api: ${options.testing.api}
  a11y: ${options.testing.a11y}
  security: ${options.testing.security}
${sourceBlock}${apiBlock}
environments: {}

identities: {}

data:
  strategy: manual
  ownerMarker: qa-ai-stlc

selectors:
  policy: playwright-default
  testIdAttribute: data-testid

agents:
  parallelism: 1
  spokeTimeoutSeconds: 60
  retries: 1
`;
}

// Runtime-only subdirectories (development plan section 3.2): everything else under `.qa/` is
// meant to be committed.
export const QA_GITIGNORE = `# Generated by "qa init".
/runs/
/evidence/
/auth/
`;
